apiVersion: gpte.redhat.com/v1
kind: AgnosticVRepo
metadata:
  name: gpte-agnosticv
spec:
  url: git@github.com:redhat-gpe/agnosticv.git
  ref: master
  sshKey: agnosticv-operator-sshkey
  babylon_anarchy_roles:
  - name: babylon_anarchy_governor
    src: https://github.com/redhat-gpte-devopsautomation/babylon_anarchy_governor.git
    version: main

